PersonalStockSystemTest/Controllers/StonkTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PersonalStockSystemTest.Models;
using PersonalStockSystemTest.EFModel;
using System.Threading.Tasks;
using System.IO;
using HtmlAgilityPack;
using System.Text;


namespace PersonalStockSystemTest.Controllers
{
    public class StonkTablesController : Controller
    {
        StonkDBEntities db = new StonkDBEntities();
        public ActionResult Index()
        {
            DBmanager dbmanager = new DBmanager();
            var stonks = dbmanager.GetStonks();
            ViewBag.stonks = stonks;
            model_List model_List = new model_List();
            model_List.Init();
            return View(model_List);


        }
        public static bool isValidURL(string url)
        {
            WebRequest webRequest = WebRequest.Create(url);
            WebResponse webResponse;
            try
            {
                webResponse = webRequest.GetResponse();
            }
            catch //If exception thrown then couldn't get response from address
            {
                return false;
            }
            return true;
        }
        public JsonResult GetCrawler(int id)
        {
            model_List model = new model_List();
            var stonkID = id.ToString();
            return Json(data: model.GetPythonJson(stonkID), JsonRequestBehavior.AllowGet);
        }
        //public ActionResult Test()
        //{
        //    Crawler model = new Crawler();
        //    string SourceURL_1 = "http://www.coolpc.com.tw/evaluate.phpsdfsdfanlksjfiojsidhfsdfsdfsdfsdf";
        //    string SourceURL_2 = "https://www.cnyes.com/twstock/2330";


        //    string Endpoint = "";
        //    if (isValidURL(SourceURL_1))
        //    {
        //        model.dataSource = "目前使用第一個資料來源";
        //        Endpoint = SourceURL_1;
        //    }
        //    else if (isValidURL(SourceURL_2))
        //    {
        //        model.dataSource = "目前使用第二個資料來源~";
        //        Endpoint = SourceURL_2;
        //    }
        //    else
        //    {
        //        model.dataSource = "兩個資料來源都掛惹~ zzz";
        //    }
        //    //-----------------------------------------------------------------------------------------
        //    WebClient url = new WebClient();
        //    //Note: 將網頁來源資料暫存到記憶體內
        //    MemoryStream ms = new MemoryStream(url.DownloadData(Endpoint));
        //    //Note: 使用預設編碼讀入 HTML  ,此為第三方套件 HtmlAgilityPack
        //    HtmlDocument doc = new HtmlDocument();
        //    doc.Load(ms, Encoding.Default);
        //   //*********************************
        //   //< h3 class="jsx-162737614 rise">30.25</h3>
        //    var priceNode = doc.DocumentNode.SelectSingleNode("//h3[@class='jsx-162737614 rise']");
        //    if (priceNode != null)
        //    {
        //        string priceText = priceNode.InnerText;
        //        model.data1 = priceText;
        //    }
        //    else if (priceNode == null)
        //    {
        //         priceNode = doc.DocumentNode.SelectSingleNode("//h3[@class='jsx-162737614 fall']");
        //        string priceText = priceNode.InnerText;
        //        model.data1 = priceText;
        //    }
        //    else
        //    {
        //        model.data1 = "無法獲取股票價格";
        //    }
        //    TempData["data1"]= model.data1;
        //    return View(model);
        //}

        public ActionResult Search()
        {
     
            model_List model_List = new model_List();
            model_List.Init();
            //----------爬蟲----------------
          
            return View(model_List);

        }
        [HttpPost]
        public ActionResult Search(model_List model_List)
        {          
            TempData["Msg"] = model_List.Search();
            TempData["StonkID"] = model_List.GetID();
            

            //Crawler model = new Crawler();  
            //string SourceURL_1 = "http://www.coolpc.com.tw/evaluate.phpsdfsdfanlksjfiojsidhfsdfsdfsdfsdf";
            //string SourceURL_2 = $"https://www.cnyes.com/twstock/{key}";


            //string Endpoint = "";
            //if (isValidURL(SourceURL_1))
            //{
            //    model.dataSource = "目前使用第一個資料來源";
            //    Endpoint = SourceURL_1;
            //}
            //else if (isValidURL(SourceURL_2))
            //{
            //    model.dataSource = "目前使用第二個資料來源~";
            //    Endpoint = SourceURL_2;
            //}
            //else
            //{
            //    model.dataSource = "兩個資料來源都掛惹~ zzz";
            //}
            ////-----------------------------------------------------------------------------------------
            //WebClient url = new WebClient();
            ////Note: 將網頁來源資料暫存到記憶體內
            //MemoryStream ms = new MemoryStream(url.DownloadData(Endpoint));
            ////Note: 使用預設編碼讀入 HTML  ,此為第三方套件 HtmlAgilityPack
            //HtmlDocument doc = new HtmlDocument();
            //doc.Load(ms, Encoding.Default);
            ////*********************************
            ////< h3 class="jsx-162737614 rise">30.25</h3>
            //var priceNode = doc.DocumentNode.SelectSingleNode("//h3[@class='jsx-162737614 rise']");
            //if (priceNode != null)
            //{
            //    string priceText = priceNode.InnerText;
            //    model.data1 = priceText;
            //}
            //else if (priceNode == null)
            //{
            //    priceNode = doc.DocumentNode.SelectSingleNode("//h3[@class='jsx-162737614 fall']");
            //    string priceText = priceNode.InnerText;
            //    model.data1 = priceText;
            //}
            //else
            //{
            //    model.data1 = "無法獲取股票價格";
            //}
            //TempData["data1"] = model.data1;
            TempData["Msg"] = model_List.Search();
            return View(model_List);
        }
        public ActionResult Create()
        {
            //DBmanager dbmanager = new DBmanager();
            ////var stonks = dbmanager.GetStonks();
            //CRUD stonks = new CRUD();
            //stonks.Search(id);
            model_Create model_crate = new model_Create();
        
            return View();
        }
        [HttpPost]
        public ActionResult Create(model_Create model_crate)
        {
            TempData["Msg"] = model_crate.Create();
            
            return View();
        }
        public ActionResult Delete(int id)
        {
            model_Edit model_Delete = new model_Edit();
            model_Delete.Load(id);
            return View(model_Delete);
        }
        [HttpPost]
        public ActionResult Delete(model_Edit model_edit)
        {
           
            TempData["Msg"] = model_edit.Delete();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            model_Edit model_edit = new model_Edit();
            model_edit.Load(id);
            return View(model_edit);
        }
        [HttpPost]
        public ActionResult Edit(model_Edit model_edit)
        {

            TempData["Msg"] = model_edit.edit();
            return RedirectToAction("Index");
        }
    }
}

PersonalStockSystemTest/Views/StonkTables/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

PersonalStockSystemTest/Views/StonkTables/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

PersonalStockSystemTest/Views/StonkTables/Create.cshtml
@model PersonalStockSystemTest.Models.model_Create

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm("Create", "StonkTables", FormMethod.Post, new { }))
{
    <table class="table table-bordered">
        <tr>

            <th>交易時間</th>
            <th>股票代號</th>
            <th>股票名稱</th>
            <th>交易種類</th>
            <th>股數</th>
            <th>單價</th>
            <th>手續費</th>
            <th>交易稅</th>

        </tr>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <tr>
            @*資料輸入*@
            <td>
                @Html.EditorFor(model => model.CreateTable.time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateTable.time, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.EditorFor(model => model.CreateTable.stonkID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateTable.stonkID, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.EditorFor(model => model.CreateTable.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateTable.name, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.EditorFor(model => model.CreateTable.type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateTable.type, "", new { @class = "text-danger" })

            </td>
            <td>
                @Html.EditorFor(model => model.CreateTable.num, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateTable.num, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.EditorFor(model => model.CreateTable.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateTable.price, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.EditorFor(model => model.CreateTable.tax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateTable.tax, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.EditorFor(model => model.CreateTable.fax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateTable.fax, "", new { @class = "text-danger" })
            </td>
        </tr>


    </table>

    <div class="btn">

        <input class="Search" type="submit" value="新增" />

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <script>
    $(function () {
        let Msg = "@TempData["Msg"]";
        if (Msg != null && Msg != "") {
            alert(Msg);
        }
    });
    </script>
}

PersonalStockSystemTest/Views/StonkTables/Delete.cshtml
@model PersonalStockSystemTest.Models.model_Edit

@{
    ViewBag.Title = "Delete";
}

    <h3>你確定要刪除嗎0.0?</h3>
    <div>
        @using (Html.BeginForm("Delete", "StonkTables", FormMethod.Post))
        {
            @Html.HiddenFor(x => x.UpdateData.id)
            <hr />
            //資料顯示
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.UpdateData.id)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UpdateData.id)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UpdateData.stonkID)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UpdateData.stonkID)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UpdateData.type)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UpdateData.type)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UpdateData.time)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UpdateData.time)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UpdateData.num)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UpdateData.num)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UpdateData.price)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UpdateData.price)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UpdateData.tax)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UpdateData.tax)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UpdateData.fax)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UpdateData.fax)
                </dd>

            

            </dl>


            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <button type="submit" class="btn btn-danger">刪除</button>
                        @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>

PersonalStockSystemTest/Views/StonkTables/Details.cshtml
@model PersonalStockSystemTest.EFModel.StonkTable

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>StonkTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.stonkID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.stonkID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.num)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.num)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.initDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.initDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.total)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PersonalStockSystemTest/Views/StonkTables/Edit.cshtml
@model PersonalStockSystemTest.Models.model_Edit
@using PersonalStockSystemTest.EFModel;
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@using (Html.BeginForm("Edit", "StonkTables", FormMethod.Post))
{

    @Html.HiddenFor(x => x.UpdateData.id)
    <table class="table table-bordered">
        <tr>

            <th>交易時間</th>
            <th>股票代號</th>
            <th>股票名稱</th>
            <th>交易種類</th>
            <th>股數</th>
            <th>單價</th>
            <th>手續費</th>
            <th>交易稅</th>

        </tr>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @*資料顯示*@
        <tr>
            <td>@Html.DisplayFor(s => Model.UpdateData.time) </td>
            <td>@Html.DisplayFor(s => Model.UpdateData.stonkID) </td>
            <td>@Html.DisplayFor(s => Model.UpdateData.name) </td>
            <td>@Html.DisplayFor(s => Model.UpdateData.type) </td>
            <td>@Html.DisplayFor(s => Model.UpdateData.num) </td>
            <td>@Html.DisplayFor(s => Model.UpdateData.price) </td>
            <td>@Html.DisplayFor(s => Model.UpdateData.tax) </td>
            <td>@Html.DisplayFor(s => Model.UpdateData.fax) </td>

        </tr>


        <tr>
            <td>
                @Html.TextBoxFor(model => model.UpdateData.time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdateData.time, "", new { @class = "text-danger" })
            </td>

            <td>
                @Html.TextBoxFor(model => model.UpdateData.stonkID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdateData.stonkID, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(model => model.UpdateData.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdateData.name, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(model => model.UpdateData.type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdateData.type, "", new { @class = "text-danger" })

            </td>
            <td>
                @Html.TextBoxFor(model => model.UpdateData.num, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdateData.num, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(model => model.UpdateData.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdateData.price, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(model => model.UpdateData.tax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdateData.tax, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.TextBoxFor(model => model.UpdateData.fax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdateData.fax, "", new { @class = "text-danger" })
            </td>

        </tr>
    </table>
    //表單送出確認
    <div class="btn">

        <input class="Search" type="submit" value="確認" />

    </div>

}


    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

PersonalStockSystemTest/Views/StonkTables/Index.cshtml
@using PersonalStockSystemTest.EFModel;

@model PersonalStockSystemTest.Models.model_List


@{ List<StonkTable> stonks = ViewBag.stonks; }
@{ ViewBag.Title = "Home Page"; }

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
@*搜尋*@
<main>
    <section class="filter">
        
        @using (Html.BeginForm("Search", "StonkTables", FormMethod.Post, new { }))  {<table>
        <tr>
            <td class="first"><label for="StockNum">股票代號</label></td>
            <td class="StockN" style="border-top: 1px solid rgb(0, 0, 0)">
                @Html.DropDownListFor(x => x.stID, Model.select, new { @style = "background-color:white" })

            </td>
        </tr>

        @*<tr>
                <td class="first"><label for="TradeType">交易種類</label></td>
                <td class="StockN">
                    <select name=" TradeTyppe">
                        <option value="">請選擇</option>
                        <option value="買">買</option>
                        <option value="賣">賣</option>
                    </select>
                </td>
            </tr>
        <tr>
                <td class="first"><label for="TradeTime">交易時間</label></td>
                <td class="StockN">
                    <input type="date" value="date" name="date" /><span style="color: gray">~</span><input type="date" name="date" />
                </td>
            </tr>*@
    </table>
                    <div class="btn">

                        <input class="Search" type="submit" value="查詢" />

                    </div>}
    </section>
    @*資料顯示*@
    <section class="StonkData">
        <div class="scroll">
            <table border="1">
                <tr>
                    <th>序號</th>
                    <th>交易時間</th>
                    <th>股票代號</th>
                    <th>股票名稱</th>
                    <th>交易種類</th>
                    <th>股數</th>
                    <th>單價</th>
                    <th>價金</th>
                    <th>手續費</th>
                    <th>交易稅</th>
                    <th>應收付款</th>
                    <th>功能</th>
                </tr>

                @foreach (var item in Model.Log_List)
                {
    <tr>
        <td>@Html.DisplayFor(s => item.id) </td>
        @{ DateTime dateTime = (DateTime)item.time;
            string str = dateTime.ToString("yyyy-MM-dd"); }
        <td>@Html.DisplayFor(s => str) </td>
        <td>@Html.DisplayFor(s => item.stonkID) </td>
        <td>@Html.DisplayFor(s => item.name) </td>
        <td>@Html.DisplayFor(s => item.type) </td>
        <td>@Html.DisplayFor(s => item.num) </td>
        <td>@Html.DisplayFor(s => item.price) </td>
        @{ var totalPrice = item.price * item.num; }
        <td>@Html.DisplayFor(s => totalPrice) </td>
        <td>@Html.DisplayFor(s => item.tax) </td>
        <td>@Html.DisplayFor(s => item.fax) </td>
        <td>
            @{ double AR = 0;
                if (item.type == "買")
                {
                    AR = (double)totalPrice * -1;
<span style="color:red">
    @Html.DisplayFor(s => AR)
</span>}
else
{
<span style="color:forestgreen">
    @Html.DisplayFor(s => totalPrice)
</span>} }
        </td>
        <td>

            <button type="button" class="btn btn-warning" onclick="location.href = '@Url.Action("Edit")?id=@item.id'">編輯</button>
            <button type="button" class="btn btn-danger" onclick="location.href = '@Url.Action("Delete")?id=@item.id'">刪除</button>

        </td>
    </tr>}

            </table>
        </div>

    </section>
    @section Scripts {
        <script>
    $(function () {
        let Msg = "@TempData["Msg"]";
        if (Msg != null && Msg != "") {
            alert(Msg);
        }
    });
        </script>
    }
</main>

PersonalStockSystemTest/Views/StonkTables/Search.cshtml
@model PersonalStockSystemTest.Models.model_List

@{
    ViewBag.Title = "Search";
}

<h2>Details</h2>

<div>
    <h4>StonkTable</h4>
    <hr />

    <h3>鉅亨網目前股票單價 @Html.Raw(TempData["data1"])</h3>
    @Html.Raw(TempData["data1"])
    @foreach (var item in Model.Log_List)
    {<button type="button" class="btn btn-warning" onclick="location.href = '@Url.Action("GetCrawler", "StonkTables")?id=@item.stonkID'">Get</button>}

    <table class="table table-bordered">
        <tr>
            <th>序號</th>
            <th>交易時間</th>
            <th>股票代號</th>
            <th>股票名稱</th>
            <th>交易種類</th>
            <th>股數</th>
            <th>單價</th>
            <th>價金</th>
            <th>手續費</th>
            <th>交易稅</th>
            <th>應收付款</th>

        </tr>
        @foreach (var item in Model.Log_List)
        {

            <tr>
                <td>@Html.DisplayFor(s => item.id) </td>
                @{ DateTime dateTime = (DateTime)item.time;
                    string str = dateTime.ToString("yyyy-MM-dd");
                }
                <td>@Html.DisplayFor(s => str) </td>
                <td>@Html.DisplayFor(s => item.stonkID) </td>
                <td>@Html.DisplayFor(s => item.name) </td>
                <td>@Html.DisplayFor(s => item.type) </td>
                <td>@Html.DisplayFor(s => item.num) </td>
                <td>@Html.DisplayFor(s => item.price) </td>
                @{ var totalPrice = item.price * item.num; }
                <td>@Html.DisplayFor(s => totalPrice) </td>
                <td>@Html.DisplayFor(s => item.tax) </td>
                <td>@Html.DisplayFor(s => item.fax) </td>
                <td>
                    @{ double AR = 0;
                        if (item.type == "買")
                        {
                            AR = (double)totalPrice * -1;
                            @Html.DisplayFor(s => AR)
                        }
                        else
                        {
                            @Html.DisplayFor(s => totalPrice);
                        }
                    }
                </td>
            </tr>



        }
    </table>
    @section Scripts {
        <script>
    $(function () {
        let Msg = "@TempData["Msg"]";
        if (Msg != null && Msg != "") {
            alert(Msg);
        }
    });
        </script>
    }

    <p>
        @Html.ActionLink("編輯", "Edit", new { id = Model.stID })
        @Html.ActionLink("刪除", "Delete", new { id = Model.stID })|
        @Html.ActionLink("Back to List", "Index")
    </p>

PersonalStockSystemTest/Views/StonkTables/Test.cshtml
@model PersonalStockSystemTest.Models.Crawler
@{
    ViewBag.Title = "Test";
}

<h2>Test @Model.dataSource</h2>



@Html.Raw(Model.data1)